{% set version = "0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lisreltor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lisrelToR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lisrelToR/lisrelToR_{{ version }}.tar.gz
  sha256: 6bbebbdd6f78ae5d503a4d53558c709233e6e94fe8206f62d5edca3d5b41b4a7

build:
  number: 2
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('lisrelToR')"           # [not win]
    - "\"%R%\" -e \"library('lisrelToR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lisrelToR
  license: GPL-2.0-only
  summary: This is an unofficial package aimed at automating the import of LISREL output in R.  This package or its maintainer is not in any way affiliated with the creators of LISREL and SSI, Inc.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
